//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NaghiEDMContainer : DbContext
    {
        public NaghiEDMContainer()
            : base("name=NaghiEDMContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Country> CountrySet { get; set; }
        public virtual DbSet<City> CitySet { get; set; }
        public virtual DbSet<ContactType> ContactTypeSet { get; set; }
        public virtual DbSet<DoneContact> DoneContactSet { get; set; }
        public virtual DbSet<UserGroup> UserGroupSet { get; set; }
        public virtual DbSet<Role> RoleSet { get; set; }
        public virtual DbSet<AssignedRole> AssignedRoleSet { get; set; }
        public virtual DbSet<Log> LogSet { get; set; }
        public virtual DbSet<GoodGroup> GoodGroupSet { get; set; }
        public virtual DbSet<Good> GoodSet { get; set; }
        public virtual DbSet<Donate> DonateSet { get; set; }
        public virtual DbSet<DonateRow> DonateRowSet { get; set; }
        public virtual DbSet<PaymentType> PaymentTypeSet { get; set; }
        public virtual DbSet<Inistitute> InistituteSet { get; set; }
        public virtual DbSet<DailyPoints> DailyPointsSet { get; set; }
        public virtual DbSet<News> NewsSet { get; set; }
        public virtual DbSet<Gallary> GallarySet { get; set; }
        public virtual DbSet<Photo> PhotoSet { get; set; }
        public virtual DbSet<State> StateSet { get; set; }
    }
}
